### PR TITLE
(+) #9 Allow methods to be ignored by NoWeaving

### LINKED ISSUE #9: Allow methods to be ignored by NoWeaving
Ignore argument weaving when method is decorated by this attribute.

### PR DESCRIPTION
**Pull request by alexfdezsauco**
Fixes #9.

### Changes proposed in this pull request:

- Allow methods to be ignored by NoWeaving

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
Looks great and I believe we are nearly there. There are more weavers that can weave methods (e.g. change notifications, etc). Did you check all of them?

**Comment by alexfdezsauco** [comment]
Let me check

**Comment by alexfdezsauco** [comment]
Looks like ProcessMethod of Argument weavers. I don't find another weaver that process method.

**Comment by GeertvanHorrik** [comment]
Excellent! In that case we can merge & people should file a report if it's not working as expected.

**Pull request merged**
